name: Tests
on: [push]

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
          #- windows-latest
        dc:
          - dmd-latest
          - dmd-2.109.1
          - ldc-latest
          - ldc-1.40.0
        buildConf:
          - Static
          - Dynamic
        include:
          - os: macOS-latest
            dc: ldc-1.40.0
            buildConf: Dynamic
          - os: macOS-latest
            dc: ldc-1.40.0
            buildConf: Static

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Install system dependencies                                           
        uses: lyricwulf/abc@v1                                                      
        with:                                                                                  
          linux: libzip-dev
          macos: libzip

      - name: Try to build the lib
        run: dub build -c "library${{ matrix.buildConf }}"

      - name: Run tests
        run: dub test -b unittest-cov -c "unittest${{ matrix.buildConf }}"

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
