name: Tests
on: [push, pull_request]

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- windows-latest
          #- macOS-latest
        dc:
          - dmd-latest
          - dmd-2.102.0
          - ldc-latest
          - ldc-1.32.2

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Install system dependencies                                           
        uses: lyricwulf/abc@v1                                                      
        with:                                                                                  
          linux: libzip-dev
                      
      - name: Try to build the lib
        run: dub build

      - name: Run tests
        run: dub test -b unittest-cov

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
